/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->StateSpace_DSTATE);
   memcpy(&pDst->StateSpace_DSTATE, &pSrc->StateSpace_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin);
   memcpy(&pDst->lastSin, &pSrc->lastSin, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos);
   memcpy(&pDst->lastCos, &pSrc->lastCos, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_g);
   memcpy(&pDst->lastSin_g, &pSrc->lastSin_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_m);
   memcpy(&pDst->lastCos_m, &pSrc->lastCos_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_m);
   memcpy(&pDst->lastSin_m, &pSrc->lastSin_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_i);
   memcpy(&pDst->lastCos_i, &pSrc->lastCos_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_k);
   memcpy(&pDst->lastSin_k, &pSrc->lastSin_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_a);
   memcpy(&pDst->lastCos_a, &pSrc->lastCos_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_kg);
   memcpy(&pDst->lastSin_kg, &pSrc->lastSin_kg, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_l);
   memcpy(&pDst->lastCos_l, &pSrc->lastCos_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastSin_p);
   memcpy(&pDst->lastSin_p, &pSrc->lastSin_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->lastCos_h);
   memcpy(&pDst->lastCos_h, &pSrc->lastCos_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable);
   memcpy(&pDst->systemEnable, &pSrc->systemEnable, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_a);
   memcpy(&pDst->systemEnable_a, &pSrc->systemEnable_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_k);
   memcpy(&pDst->systemEnable_k, &pSrc->systemEnable_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_d);
   memcpy(&pDst->systemEnable_d, &pSrc->systemEnable_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_e);
   memcpy(&pDst->systemEnable_e, &pSrc->systemEnable_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->systemEnable_g);
   memcpy(&pDst->systemEnable_g, &pSrc->systemEnable_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->clockTickCounter);
   memcpy(&pDst->clockTickCounter, &pSrc->clockTickCounter, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->StateSpace_IWORK);
   memcpy(&pDst->StateSpace_IWORK, &pSrc->StateSpace_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->StateSpace_IWORK_p);
   memcpy(&pDst->StateSpace_IWORK_p, &pSrc->StateSpace_IWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.CTOutputIncnstWithState);
   memcpy(&pDst->ModelData.CTOutputIncnstWithState, &pSrc->ModelData.CTOutputIncnstWithState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

